GET http://localhost:3000/api/camerass
###
GET http://localhost:3000/api/teddies/5be9c8541c9d440000665243
###
POST http://localhost:3000/api/teddies/order
Content-Type: application/json

{
    "contact":{
        "firstName": "Quentin",
        "lastName": "Quentin",
        "address": "Quentin",
        "city": "Quentin",
        "email": "Quentin"
    },
    "products": [
        "5be9c8541c9d440000665243"
    ]

}